In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
df = pd.read_csv('D:/DL/ANN/bank-customer-loyalty/\dataset/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
# Create independent variable matrix and label
X = df.iloc[:,  3:13]
y = df['Exited']
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [8]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [10]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le_1 = LabelEncoder()
X['Geography'] = le_1.fit_transform(X['Geography'])

le_2 = LabelEncoder()
X['Gender'] = le_1.fit_transform(X['Gender'])

X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [16]:
encoder = OneHotEncoder(handle_unknown='ignore')
encoder_df = pd.DataFrame(encoder.fit_transform(X[['Geography']]).toarray())

#Merge with the X
X = X.join(encoder_df)
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary    0    1    2  
0          1               1        101348.88  1.0  0.0  0.0  
1          0               1        112542.58  0.0  0.0  1.0  
2          1               0        113931.57  1.0  0.0  0.0  
3          0               0         93826.63  1.0  0.0  0.0  
4          1               1         79084.10  0.0  0.0  1.0

In [23]:
X = X.drop(['Geography', 0], axis=1)
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary    1    2  
0               1        101348.88  0.0  0.0  
1               1        112542.58  0.0  1.0  
2               0        113931.57  0.0  0.0  
3               0         93826.63  0.0  0.0  
4               1         79084.10  0.0  1.0

In [27]:
X = X.values
y= y.values

X

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0134888e+05,
        0.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 0.0000000e+00, 4.1000000e+01, ..., 1.1254258e+05,
        0.0000000e+00, 1.0000000e+00],
       [5.0200000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.1393157e+05,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 4.2085580e+04,
        0.0000000e+00, 0.0000000e+00],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 9.2888520e+04,
        1.0000000e+00, 0.0000000e+00],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 3.8190780e+04,
        0.0000000e+00, 0.0000000e+00]])

In [28]:
# Split our data into training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
# Feature scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [33]:
# Build neuron network
from tensorflow import keras

model = keras.Sequential(
    [
        keras.layers.Dense(
            7, activation="relu", input_shape=(X_train.shape[-1],)
        ),
        keras.layers.Dense(256, activation="relu"),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(256, activation="relu"),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(1, activation="sigmoid"),
    ]
)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 84        
_________________________________________________________________
dense_1 (Dense)              (None, 256)               2048      
_________________________________________________________________
dropout (Dropout)            (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               65792     
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 257       
Total params: 68,181
Trainable params: 68,181
Non-trainable params: 0
____________________________________________________

In [34]:
#compile
model.compile(optimizer='adam', loss='binary_crossentropy',   metrics=['accuracy'])

In [35]:
#train neural network
model.fit(X_train,  y_train, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4843 - accuracy: 0.7964
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8254
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3902 - accuracy: 0.8342
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3753 - accuracy: 0.8447
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3686 - accuracy: 0.8461
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3581 - accuracy: 0.8521
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8585: 0s - loss: 0.3528 - accuracy: 0.85
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3495 - accuracy: 0.8586
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8608
Epoch 10/100
250/250 [==============================] -

In [39]:
#predict
y_pred = model.predict(X_test)
y_pred = (y_pred>0.5).astype(int)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [41]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[1543,   64],
       [ 205,  188]], dtype=int64)